version: '3.7'
services:
  pgsql:
    container_name: pgsql
    build:
      context: ./postgres
      dockerfile: dockerfile.postgres
    ports:
      - '5432:5432'
    restart: always  
    volumes:
      - ./postgres/db:/var/lib/postgresql/data      
    env_file:
      - ./env/postgres.env

  app-django:
    container_name: app-django
    build:
      context: ./app
      dockerfile: ./dockerfile.app
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
    #command: uwsgi --http :8000 --module acd_app.wsgi
    #command: uwsgi --socket acd_app.sock --module acd_app.wsgi --chmod-socket=666
    #command: uwsgi --socket :8000 --master --enable-threads --module acd_app.wsgi
    #stdin_open: true
    ports:
      - '8000:8000'  
    depends_on:
      - pgsql
    restart: on-failure
    volumes:
      - ./app:/app
      - static_data:/app/static     
    env_file:
      - ./env/app.env
      
volumes:
  static_data: