# Generated by Django 4.0.1 on 2022-01-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T02TipoCalculo',
            fields=[
                ('t02_id_tipo_calculo', models.AutoField(db_column='T02_ID_TIPO_CALCULO', primary_key=True, serialize=False)),
                ('t02_desc_tipo_calculo', models.CharField(blank=True, db_column='T02_DESC_TIPO_CALCULO', max_length=70, null=True)),
            ],
            options={
                'verbose_name': 'T02 - Tipo de Cálculo',
                'verbose_name_plural': 'T02 - Tipos de Cálculo',
            },
        ),
        migrations.CreateModel(
            name='T03Instancia',
            fields=[
                ('t03_id_instancia', models.AutoField(db_column='T03_ID_INSTANCIA', primary_key=True, serialize=False)),
                ('t03_sigla_instancia', models.CharField(blank=True, db_column='T03_SIGLA_INSTANCIA', max_length=4, null=True)),
                ('t03_tipo_atuacao_tribunal', models.CharField(blank=True, db_column='T03_TIPO_ATUACAO_TRIBUNAL', max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'T03 - Tipo de Instância',
                'verbose_name_plural': 'T03 - Tipos de Instâncias',
            },
        ),
        migrations.CreateModel(
            name='T05SituacaoUniaoProcesso',
            fields=[
                ('t05_id_situacao_uniao', models.AutoField(db_column='T05_ID_SITUACAO_UNIAO', primary_key=True, serialize=False)),
                ('t05_desc_situacao_uniao', models.CharField(blank=True, db_column='T05_DESC_SITUACAO_UNIAO', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'T05 - Situação da União',
                'verbose_name_plural': 'T05 - Situação da União',
            },
        ),
        migrations.CreateModel(
            name='T06TipoParecer',
            fields=[
                ('t06_id_tipo_parecer', models.AutoField(db_column='T06_ID_TIPO_PARECER', primary_key=True, serialize=False)),
                ('t06_desc_tipo_parecer', models.CharField(blank=True, db_column='T06_DESC_TIPO_PARECER', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'T06 - Tipo de parecer',
                'verbose_name_plural': 'T06 - Tipos de parecer',
            },
        ),
        migrations.CreateModel(
            name='T07ObjetoAcao',
            fields=[
                ('t07_id_objeto_acao', models.AutoField(db_column='T07_ID_OBJETO_ACAO', primary_key=True, serialize=False)),
                ('t07_desc_objeto_acao', models.CharField(blank=True, db_column='T07_DESC_OBJETO_ACAO', max_length=255, null=True)),
                ('t07_num_grupo', models.DecimalField(blank=True, db_column='T07_NUM_GRUPO', decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'verbose_name': 'T07 - Objeto da ação',
                'verbose_name_plural': 'T07 - Objetos da ação',
            },
        ),
        migrations.CreateModel(
            name='T08OrgaoRepresentado',
            fields=[
                ('t08_id_orgao_representado', models.AutoField(db_column='T08_ID_ORGAO_REPRESENTADO', primary_key=True, serialize=False)),
                ('t08_desc_orgao_representado', models.CharField(blank=True, db_column='T08_DESC_ORGAO_REPRESENTADO', max_length=70, null=True)),
                ('t08_cod_orgao_vinculado', models.DecimalField(blank=True, db_column='T08_COD_ORGAO_VINCULADO', decimal_places=0, max_digits=18, null=True)),
                ('t08_sigla_abrangencia_demanda', models.CharField(blank=True, db_column='T08_SIGLA_ABRANGENCIA_DEMANDA', max_length=6, null=True)),
            ],
            options={
                'verbose_name': 'T08 - Órgão representado',
                'verbose_name_plural': 'T08 - Órgãos representado',
            },
        ),
        migrations.CreateModel(
            name='T09Necap',
            fields=[
                ('t09_id_necap', models.AutoField(db_column='T09_ID_NECAP', primary_key=True, serialize=False)),
                ('t09_desc_necap', models.CharField(blank=True, db_column='T09_DESC_NECAP', max_length=50, null=True)),
                ('t09_cod_senha', models.CharField(db_column='T09_COD_SENHA', max_length=8)),
                ('t09_cod_necap_regional', models.DecimalField(blank=True, db_column='T09_COD_NECAP_REGIONAL', decimal_places=0, max_digits=18, null=True)),
                ('t09_cod_abrangencia_atuacao', models.CharField(blank=True, db_column='T09_COD_ABRANGENCIA_ATUACAO', max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'T09 - Lista NECAP',
                'verbose_name_plural': 'T09 - Lista NECAPs',
            },
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=30, verbose_name='Sobrenome')),
                ('estado', models.CharField(max_length=5, verbose_name='Estado')),
            ],
            options={
                'verbose_name': '1. Nome',
                'verbose_name_plural': '1. Nomes',
            },
        ),
        migrations.CreateModel(
            name='Tribunais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Tribunal')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': '2. Tribunal',
                'verbose_name_plural': '2. Tribunais',
            },
        ),
        migrations.CreateModel(
            name='T14ResponsavelProcesso',
            fields=[
                ('t14_id', models.AutoField(db_column='T14_ID', primary_key=True, serialize=False)),
                ('t14_nome_responsavel', models.CharField(blank=True, db_column='T14_NOME_RESPONSAVEL', max_length=70, null=True)),
                ('t14_cod_necap', models.ForeignKey(blank=True, db_column='T14_COD_NECAP', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.t09necap')),
            ],
            options={
                'verbose_name': 'T14 - Responsável Processo',
                'verbose_name_plural': 'T14 - Responsável Processo',
            },
        ),
        migrations.CreateModel(
            name='T04OrigemProcesso',
            fields=[
                ('t04_id_unidade', models.AutoField(db_column='T04_ID_UNIDADE', primary_key=True, serialize=False)),
                ('t04_num_ordem', models.DecimalField(blank=True, db_column='T04_NUM_ORDEM', decimal_places=0, max_digits=18, null=True)),
                ('t04_num_regiao', models.CharField(blank=True, db_column='T04_NUM_REGIAO', max_length=3, null=True)),
                ('t04_desc_unidade', models.CharField(blank=True, db_column='T04_DESC_UNIDADE', max_length=50, null=True)),
                ('t04_sigla_unidade', models.CharField(blank=True, db_column='T04_SIGLA_UNIDADE', max_length=20, null=True)),
                ('t04_nome_cidade_unidade', models.CharField(blank=True, db_column='T04_NOME_CIDADE_UNIDADE', max_length=50, null=True)),
                ('t04_sigla_uf_unidade', models.CharField(blank=True, db_column='T04_SIGLA_UF_UNIDADE', max_length=2, null=True)),
                ('t04_cod_necap', models.ForeignKey(blank=True, db_column='T04_COD_NECAP', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.t09necap')),
            ],
            options={
                'verbose_name': 'T04 - Origem do Processo',
                'verbose_name_plural': 'T04 - Origens do Processo',
            },
        ),
        migrations.CreateModel(
            name='T01Processo',
            fields=[
                ('t01_id_processo', models.AutoField(db_column='T01_ID_PROCESSO', primary_key=True, serialize=False)),
                ('t01_num_processo', models.CharField(db_column='T01_NUM_PROCESSO', max_length=30)),
                ('t01_nome_exequente', models.CharField(blank=True, db_column='T01_NOME_EXEQUENTE', max_length=70, null=True)),
                ('t01_qtd_exequente', models.IntegerField(blank=True, db_column='T01_QTD_EXEQUENTE', null=True)),
                ('t01_num_parecer', models.CharField(blank=True, db_column='T01_NUM_PARECER', max_length=20, null=True)),
                ('t01_vr_autor', models.FloatField(blank=True, db_column='T01_VR_AUTOR', null=True)),
                ('t01_vr_uniao', models.FloatField(blank=True, db_column='T01_VR_UNIAO', null=True)),
                ('t01_dt_envio_necap', models.DateTimeField(blank=True, db_column='T01_DT_ENVIO_NECAP', null=True)),
                ('t01_dt_prazo_advogado', models.DateTimeField(blank=True, db_column='T01_DT_PRAZO_ADVOGADO', null=True)),
                ('t01_dt_recebimento_tecnico', models.DateTimeField(blank=True, db_column='T01_DT_RECEBIMENTO_TECNICO', null=True)),
                ('t01_dt_saida_necap', models.DateTimeField(blank=True, db_column='T01_DT_SAIDA_NECAP', null=True)),
                ('t01_obs_processo', models.CharField(blank=True, db_column='T01_OBS_PROCESSO', max_length=200, null=True)),
                ('t01_nome_responsavel', models.CharField(blank=True, db_column='T01_NOME_RESPONSAVEL', max_length=70, null=True)),
                ('t01_sn_pericia', models.CharField(blank=True, db_column='T01_SN_PERICIA', max_length=1, null=True)),
                ('t01_dt_digitacao', models.DateTimeField(blank=True, db_column='T01_DT_DIGITACAO', null=True)),
                ('t01_num_acao_originaria', models.CharField(blank=True, db_column='T01_NUM_ACAO_ORIGINARIA', max_length=30, null=True)),
                ('t01_desc_necap', models.DecimalField(blank=True, db_column='T01_DESC_NECAP', decimal_places=0, max_digits=18, null=True)),
                ('t01_cod_instancia', models.ForeignKey(blank=True, db_column='T01_COD_INSTANCIA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.t03instancia')),
                ('t01_cod_objeto_acao', models.ForeignKey(blank=True, db_column='T01_COD_OBJETO_ACAO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.t07objetoacao')),
                ('t01_cod_orgao_representado', models.ForeignKey(blank=True, db_column='T01_COD_ORGAO_REPRESENTADO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.t08orgaorepresentado')),
                ('t01_cod_situacao_uniao', models.ForeignKey(blank=True, db_column='T01_COD_SITUACAO_UNIAO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.t05situacaouniaoprocesso')),
                ('t01_cod_tipo_calculo', models.ForeignKey(blank=True, db_column='T01_COD_TIPO_CALCULO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.t02tipocalculo')),
                ('t01_cod_tipo_parecer', models.ForeignKey(blank=True, db_column='T01_COD_TIPO_PARECER', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.t06tipoparecer')),
                ('t01_cod_unidade', models.ForeignKey(blank=True, db_column='T01_COD_UNIDADE', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.t04origemprocesso')),
            ],
            options={
                'verbose_name': 'T01 - Dados do Processo',
                'verbose_name_plural': 'T01 - Dados dos Processos',
            },
        ),
    ]
