# Generated by Django 4.0.1 on 2022-03-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t01processo',
            options={'ordering': ['-t01_id_processo'], 'verbose_name': 'T01 - Dados do Processo', 'verbose_name_plural': 'T01 - Dados dos Processos'},
        ),
        migrations.AlterModelOptions(
            name='t02tipocalculo',
            options={'ordering': ['t02_desc_tipo_calculo'], 'verbose_name': 'T02 - Tipo de Cálculo', 'verbose_name_plural': 'T02 - Tipos de Cálculo'},
        ),
        migrations.AlterModelOptions(
            name='t03instancia',
            options={'ordering': ['t03_sigla_instancia'], 'verbose_name': 'T03 - Tipo de Instância', 'verbose_name_plural': 'T03 - Tipos de Instâncias'},
        ),
        migrations.AlterModelOptions(
            name='t04origemprocesso',
            options={'ordering': ['t04_sigla_unidade'], 'verbose_name': 'T04 - Origem do Processo', 'verbose_name_plural': 'T04 - Origens do Processo'},
        ),
        migrations.AlterModelOptions(
            name='t06tipoparecer',
            options={'ordering': ['t06_desc_tipo_parecer'], 'verbose_name': 'T06 - Tipo de parecer', 'verbose_name_plural': 'T06 - Tipos de parecer'},
        ),
        migrations.AlterModelOptions(
            name='t07objetoacao',
            options={'ordering': ['t07_desc_objeto_acao'], 'verbose_name': 'T07 - Objeto da ação', 'verbose_name_plural': 'T07 - Objetos da ação'},
        ),
        migrations.AlterModelOptions(
            name='t08orgaorepresentado',
            options={'ordering': ['t08_desc_orgao_representado'], 'verbose_name': 'T08 - Órgão representado', 'verbose_name_plural': 'T08 - Órgãos representado'},
        ),
        migrations.AlterModelOptions(
            name='t09necap',
            options={'ordering': ['t09_desc_necap'], 'verbose_name': 'T09 - Lista NECAP', 'verbose_name_plural': 'T09 - Lista NECAPs'},
        ),
        migrations.AlterModelOptions(
            name='t14responsavelprocesso',
            options={'ordering': ['t14_nome_responsavel'], 'verbose_name': 'T14 - Responsável Processo', 'verbose_name_plural': 'T14 - Responsável Processo'},
        ),
    ]
